[project]
requires-python = ">=3.13.1"

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
extend-select = [
    "D",
    "E",
    "I",
    "N",
    "W"
]

[tool.ruff.lint.pydocstyle]
convention = "google"
